<CreateAccountWindow>:
    name: "create"

    namae: namae
    email: email
    password: passw

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Create an Account"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8}
                text: "Name: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.12
                id: namae
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13}
                text: "Email: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13}
                size_hint: 0.4, 0.12
                id: email
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*2}
                text: "Password: "
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*2}
                size_hint: 0.4, 0.12
                id: passw
                multiline: False
                password: True
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.3,"y":0.25}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Already have an Account? Log In"
            on_release:
                root.manager.transition.direction = "left"
                root.login()

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Submit"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "left"
                root.submit()

<LoginWindow>:
    name: "login"

    email: email
    password: password

    FloatLayout:

        Label:
            text:"Email: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: 0.35, 0.15

        TextInput:
            id: email
            font_size: (root.width**2 + root.height**2) / 13**4
            write_tab: False
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.9}
            size_hint: 0.4, 0.15

        Label:
            text:"Password: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: 0.35, 0.15

        TextInput:
            id: password
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            password: True
            pos_hint: {"x": 0.45, "top":0.7}
            size_hint: 0.4, 0.15

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.2
            font_size: (root.width**2 + root.height**2) / 13**4
            text: "Login"
            on_release:
                root.manager.transition.direction = "down"
                root.loginBtn()

        Button:
            pos_hint:{"x":0.3,"y":0.3}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Don't have an Account? Create One"
            on_release:
                root.manager.transition.direction = "left"
                root.createBtn()

<UserWindow>:
    n: n
    email: email
    created:created
    dataloc:dataloc

    FloatLayout:
        cols:1

        FloatLayout:

            size: root.width, root.height/2

            Label:
                id: n
                pos_hint:{"x": 0.1, "top":0.9}
                size_hint:0.8, 0.2
                text: "Account Name: "

            Label:
                id: email
                pos_hint:{"x": 0.1, "top":0.8}
                size_hint:0.8, 0.2
                text: "Email: "

            Label:
                id: created
                pos_hint:{"x": 0.1, "top":0.7}
                size_hint:0.8, 0.2
                text: "Created: "

            Label:
                id: dataloc
                pos_hint:{"x": 0.1, "top":0.6}
                size_hint:0.8, 0.2
                text: "Data saved in: "

        Button:
            pos_hint:{"x":0.2, "y": 0.1}
            size_hint:0.4,0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Log Out"
            on_release:
                root.manager.transition.direction = "up"
                app.root.current = "login"


        Button:
            pos_hint:{"x":0.6,"y":0.05}
            size_hint: 0.4, 0.15
            text: "Mah Thingz Plz"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "down"
                root.mahThingz()

<ThingzWindow>:
    n: n
    dataloc: dataloc
    # thingz: thingz
    FloatLayout:
        cols:1

        FloatLayout:

            size: root.width, root.height/2
            Label:
                id: n
                pos_hint:{"x": 0.1, "top":0.9}
                size_hint:0.8, 0.2
                text: "Account Name: "

            Label:
                id: dataloc
                pos_hint:{"x": 0.1, "top":0.8}
                size_hint:0.8, 0.2
                text: "Data stored in : "

            Button:
                # from when this was but a lowly label
                # id: thingz
                pos_hint:{"x": 0.1, "top":0.6}
                size_hint:0.8, 0.2
                text: "New Thingz"
                font_size: (root.width**2 + root.height**2) / 17**4
                on_release:
                    root.manager.transition.direction = "left"
                    root.newThingz()

        Button:
            pos_hint:{"x":0.2, "y": 0.1}
            size_hint:0.4,0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Log Out"
            on_release:
                app.root.current = "login"
                root.manager.transition.direction = "up"

        Button:
            pos_hint:{"x":0.6,"y":0.05}
            size_hint: 0.4, 0.1
            text: "Check me out!"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "down"
                root.checkUser()

<Txt@Label>:
    text_size: self.size
    halign: 'right'
    size_hint_x: 0.2

<In@TextInput>:
    halign: 'center'
    size_hint_x: 0.6

<Add@Button>:
    size_hint_x: 0.2

<GetThingsFromUser@GridLayout>:
    cols:3

    # Add:
    #     text: "Add"
    #     on_release:

<OurButtons@GridLayout>:
    cols:3
<NewThingz>:
    GridLayout:
        cols: 1
        orientation: "tb-lr"
        GetThingsFromUser:
            Txt:
                text: "yo mamma"
            In:
                text: "sum text here"
            Add:
                text: "yo mamma"
            Txt:
                text: "wHYYYYYY"
            Txt:
                text: "yo mamma"
            Txt:
                text: "wHYYYYYY"
            Txt:
                text: "yo mamma"
            In:
                text: "sum text here"
            Add:
                text: "yo mamma"
            Txt:
                text: "wHYYYYYY"
            Txt:
                text: "yo mamma"
            Txt:
                text: "wHYYYYYY"
        OurButtons:
            Button:
                size_hint_x: 0.2
                text: "Log Out"
                on_release:
                    app.root.current = "login"
                    root.manager.transition.direction = "up"

            Button:
                size_hint_x: 0.3
                text: "RANDOM"
                # sets values to randint in range
                on_release:

            Button:
                size_hint_x: 0.3
                text: "SAVE??!"
                # saves current data to userfile
                on_release:
